{*******************************************************}
{                                                       }
{                    NTS Code Library                   }
{         Created by GooD-NTS ( good.nts@gmail.com )    }
{           http://ntscorp.ru/  Copyright(c) 2011       }
{          License: Mozilla Public License 1.1          }
{                                                       }
{*******************************************************}

{$IF System.CompilerVersion >= 23.0}
	{$DEFINE HAS_UNITSCOPE}
  {$DEFINE HAS_VCLSTYLES}
{$IFEND}